package view;

import java.util.ArrayList;

import controller.AdministratorController;
import model.User;
import java.awt.Color;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pc
 */
public class AdministratorView extends javax.swing.JFrame implements IAdministratorView {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private LoginView loginView;
	private AdministratorController adminController;
	/**
     * Creates new form NewJFrame2
     */	
    public AdministratorView(LoginView login) {
		getContentPane().setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
		getContentPane().setBackground(new Color(255, 192, 203));
    	loginView = login;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                        
    private void initComponents() {

    	jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.setBackground(new Color(255, 240, 245));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        userNameTxt = new javax.swing.JTextField();
        userNameTxt.setBackground(new Color(255, 240, 245));
        passTxt = new javax.swing.JTextField();
        passTxt.setBackground(new Color(255, 240, 245));
        fnameTxt = new javax.swing.JTextField();
        fnameTxt.setBackground(new Color(255, 240, 245));
        lnameTxt = new javax.swing.JTextField();
        lnameTxt.setBackground(new Color(255, 240, 245));
        typeTxt = new javax.swing.JTextField();
        typeTxt.setBackground(new Color(255, 240, 245));
        createAdministrator = new javax.swing.JButton();
        createAdministrator.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        editAdmin = new javax.swing.JButton();
        editAdmin.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        deleteAdmin = new javax.swing.JButton();
        deleteAdmin.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        findUserTxt = new javax.swing.JTextField();
        findUserTxt.setBackground(new Color(255, 240, 245));
        findAllAdmin = new javax.swing.JButton();
        findAllAdmin.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        findUserAdmin = new javax.swing.JButton();
        findUserAdmin.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        logoutAdmin = new javax.swing.JButton();
        logoutAdmin.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
        errorUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "UserName", "Password", "FirstName", "LastName", "Type"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("UserName:");

        jLabel2.setText("Password:");

        jLabel3.setText("FirstName:");

        jLabel4.setText("LastName:");

        jLabel5.setText("Type:");

        createAdministrator.setText("Create");
        createAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdministratorActionPerformed(evt);
            }
        });

        editAdmin.setText("Edit");
        editAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdminActionPerformed(evt);
            }
        });

        deleteAdmin.setText("Delete");
        deleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAdminActionPerformed(evt);
            }
        });

        jLabel6.setText("UserName:");

        findAllAdmin.setText("Find All");
        findAllAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findAllAdminActionPerformed(evt);
            }
        });

        findUserAdmin.setText("Find User");
        findUserAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findUserAdminActionPerformed(evt);
            }
        });

        logoutAdmin.setText("Logout");
        logoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(91, 91, 91))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(editAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(createAdministrator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deleteAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(findUserAdmin)
                                .addGap(30, 30, 30)
                                .addComponent(findAllAdmin)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutAdmin)
                                .addGap(47, 47, 47))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(findUserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorUser)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findUserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(findAllAdmin)
                            .addComponent(findUserAdmin))))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAdministrator))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAdmin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteAdmin)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(logoutAdmin)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(typeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorUser)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>                        

    private void createAdministratorActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    	adminController.AddNewUser(userNameTxt.getText(), passTxt.getText(), fnameTxt.getText(), lnameTxt.getText(), typeTxt.getText());
    }                                                   

    private void editAdminActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	adminController.EditUser(userNameTxt.getText(), passTxt.getText(), fnameTxt.getText(), lnameTxt.getText(), typeTxt.getText());
    }                                         

    private void deleteAdminActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	adminController.DeleteUser();
    }                                           

    private void findAllAdminActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    	adminController.SetUsers();
    }                                            

    private void findUserAdminActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	adminController.FindUser(findUserTxt.getText());
    }                                             

    private void logoutAdminActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	this.dispose();
    	loginView.setVisible(true);
    }                   
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    	int index = jTable1.getSelectedRow();
    	userNameTxt.setText(jTable1.getValueAt(index, 1).toString());
    	passTxt.setText(jTable1.getValueAt(index, 2).toString());
    	fnameTxt.setText(jTable1.getValueAt(index, 3).toString());
    	lnameTxt.setText(jTable1.getValueAt(index, 4).toString());
    	typeTxt.setText(jTable1.getValueAt(index, 5).toString());
        
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton createAdministrator;
    private javax.swing.JButton deleteAdmin;
    private javax.swing.JButton editAdmin;
    private javax.swing.JLabel errorUser;
    private javax.swing.JButton findAllAdmin;
    private javax.swing.JButton findUserAdmin;
    private javax.swing.JTextField findUserTxt;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JButton logoutAdmin;
    private javax.swing.JTextField passTxt;
    private javax.swing.JTextField typeTxt;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration                   
	@Override
	public void SetController(AdministratorController controller) {
		// TODO Auto-generated method stub
		adminController = controller;
	}

	@Override
	public void UpdateUserView() {
		// TODO Auto-generated method stub
		adminController.SetUsers();
	}

	@Override
	public void SetUsersInGrid(ArrayList<User> usersList) {
		// TODO Auto-generated method stub
		String[][] obj = new String[usersList.size()][6];
    	for(int i=0;i<usersList.size();i++){
    			obj[i][0]=""+usersList.get(i).getId();
    			obj[i][1]=usersList.get(i).getUserName();
    			obj[i][2]=usersList.get(i).getPassword();
    			obj[i][3]=usersList.get(i).getFirstName();
    			obj[i][4]=usersList.get(i).getLastName();
    			obj[i][5]=usersList.get(i).getType();
    		
    	}
    	jTable1.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                new String [] {
                        "Id", "UserName", "Password", "FirstName", "LastName", "Type"
                    }
            ));
	}

	@Override
	public void AddNewUser(String errorMsg) {
		// TODO Auto-generated method stub
		errorUser.setText(errorMsg);
	}

	@Override
	public void DeleteUser(String errorMsg) {
		// TODO Auto-generated method stub
		errorUser.setText(errorMsg);
	}

	@Override
	public void EditUser(String errorMsg) {
		// TODO Auto-generated method stub
		errorUser.setText(errorMsg);
	}

	@Override
	public void FindUser(User user, Boolean error, String errorMsg) {
		// TODO Auto-generated method stub
		if (error == false)
        {
			jTable1.removeAll();
            String[][] obj = new String[1][6];
        	obj[0][0]=""+user.getId();
        	obj[0][1]=user.getUserName();
        	obj[0][2]=user.getPassword();
        	obj[0][3]=user.getFirstName();
        	obj[0][4]=user.getLastName();
        	obj[0][5]=user.getType();
        		
        	jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    obj,
                    new String [] {
                            "Id", "UserName", "Password", "FirstName", "LastName", "Type"
                        }
                ));
			errorUser.setText(errorMsg);
        }
        else
        	errorUser.setText(errorMsg);
	}

	@Override
	public User GetSelectedUserFromGrid() {
		// TODO Auto-generated method stub
		if (jTable1.getSelectedRowCount() > 0)
        {
        	int row = jTable1.getSelectedRow();
        	User user = new User();
        	user.setId(Integer.parseInt(jTable1.getValueAt(row, 0).toString()));
        	user.setUserName(jTable1.getValueAt(row, 1).toString());
        	user.setPassword(jTable1.getValueAt(row, 2).toString());
        	user.setFirstName(jTable1.getValueAt(row, 3).toString());
        	user.setLastName(jTable1.getValueAt(row, 5).toString());
        	user.setType(jTable1.getValueAt(row, 4).toString());
            return user;
        }
        else
        	errorUser.setText("Select a row from table!");
        return null;
	}
}
