package view;

import controller.LoginController;
import java.awt.Color;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

public class LoginView extends javax.swing.JFrame implements ILoginView {

	    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private LoginController logController;
		/**
	     * Creates new form NewJFrame
	     */
	    public LoginView() {
			getContentPane().setBackground(new Color(255, 192, 203));
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jLabel1.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
	        jLabel2 = new javax.swing.JLabel();
	        jLabel2.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
	        jTextField1 = new javax.swing.JTextField();
	        jTextField1.setBackground(new Color(255, 240, 245));
	        jButton1 = new javax.swing.JButton();
	        jButton1.setBackground(new Color(255, 240, 245));
	        jButton1.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 13));
	        jPasswordField1 = new javax.swing.JPasswordField();
	        jPasswordField1.setBackground(new Color(255, 240, 245));
	        errorLabel = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jLabel1.setText("Username:");

	        jLabel2.setText("Password:");

	        jButton1.setText("Login");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        layout.setHorizontalGroup(
	        	layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(layout.createSequentialGroup()
	        			.addGap(73)
	        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
	        				.addComponent(jLabel1)
	        				.addComponent(jLabel2))
	        			.addGap(31)
	        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
	        				.addComponent(errorLabel)
	        				.addComponent(jPasswordField1, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
	        				.addComponent(jTextField1))
	        			.addContainerGap(144, Short.MAX_VALUE))
	        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
	        			.addContainerGap(182, Short.MAX_VALUE)
	        			.addComponent(jButton1)
	        			.addGap(167))
	        );
	        layout.setVerticalGroup(
	        	layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(layout.createSequentialGroup()
	        			.addGap(102)
	        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        				.addComponent(jLabel1)
	        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
	        			.addGap(18)
	        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        				.addComponent(jLabel2)
	        				.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
	        			.addGap(46)
	        			.addComponent(jButton1)
	        			.addGap(13)
	        			.addComponent(errorLabel)
	        			.addContainerGap(58, Short.MAX_VALUE))
	        );
	        getContentPane().setLayout(layout);

	        errorLabel.getAccessibleContext().setAccessibleName("errorLabel");

	        pack();
	    }// </editor-fold>                        
                    
	    @Override
	    public void SetController(LoginController controller)
	    {
	    	logController = controller;
	    }
	    
	    @Override
	    public void ValidateLog(Boolean valid, String errorMsg)
	    {
	    	if (valid==false)
            {
                errorLabel.setText(errorMsg);
            }
	    }
	    
		@SuppressWarnings("deprecation")
		private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	logController.ValidateLogin(jTextField1.getText(), jPasswordField1.getText(), this);
	    }                                        


	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel errorLabel;
	    private javax.swing.JPasswordField jPasswordField1;
	    private javax.swing.JTextField jTextField1;
	    // End of variables declaration 
	}


