package view;

import java.util.List;

import controller.RegularUserController;
import model.Cart;
import model.Product;
import model.User;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pc
 */
public class RegularUserView extends javax.swing.JFrame implements ISecretaryView{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private LoginView _loginView;
	private RegularUserController secretaryController;
    /**
     * Creates new form NewJFrame1
     */
    public RegularUserView(LoginView login) {
    	_loginView = login;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    @SuppressWarnings("serial")
	private void initComponents() {

    	jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBackground(new Color(255, 192, 203));
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTable2.setBackground(new Color(255, 240, 245));
        jLabel8 = new javax.swing.JLabel();
        fnameDoctorTxt = new javax.swing.JTextField();
        fnameDoctorTxt.setBackground(new Color(255, 240, 245));
        jLabel9 = new javax.swing.JLabel();
        lnameDoctorTxt = new javax.swing.JTextField();
        lnameDoctorTxt.setBackground(new Color(255, 240, 245));
        jLabel10 = new javax.swing.JLabel();
        cnpPatientTxt = new javax.swing.JTextField();
        cnpPatientTxt.setBackground(new Color(255, 240, 245));
        createConsult = new javax.swing.JButton();
        deleteConsult = new javax.swing.JButton();
        editConsult = new javax.swing.JButton();
        logoutConsult = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jList1.setBackground(new Color(255, 240, 245));
        errorConsult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null},
        		{null, null, null},
        		{null, null, null},
        		{null, null, null},
        	},
        	new String[] {
        		"Id", "Id_Product", "Id_Buyer"
        	}
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel8.setText("Buyer First Name:");

        jLabel9.setText("Buyer Last Name:");

        jLabel10.setText("Product ID:");

        createConsult.setText("Create");
        createConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConsultActionPerformed(evt);
            }
        });

        deleteConsult.setText("Delete");
        deleteConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConsultActionPerformed(evt);
            }
        });

        editConsult.setText("Edit");
        editConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editConsultActionPerformed(evt);
            }
        });

        logoutConsult.setText("Logout");
        logoutConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutConsultActionPerformed(evt);
            }
        });

        jLabel12.setText("Buyers List");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 441, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGap(183)
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel12)
        								.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE))))
        					.addGap(55)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(editConsult, GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        						.addComponent(deleteConsult, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(createConsult, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(cnpPatientTxt, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel10, Alignment.LEADING)
        						.addComponent(jLabel8, Alignment.LEADING)
        						.addComponent(fnameDoctorTxt, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel9, Alignment.LEADING)
        						.addComponent(lnameDoctorTxt, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        						.addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
        							.addGap(71)
        							.addComponent(logoutConsult))))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(errorConsult)))
        			.addGap(77))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(jLabel8)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(fnameDoctorTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jLabel9)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(lnameDoctorTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel10)
        				.addComponent(jLabel12))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(cnpPatientTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(37)
        					.addComponent(createConsult)
        					.addGap(18)
        					.addComponent(deleteConsult)
        					.addGap(18)
        					.addComponent(editConsult)
        					.addGap(104)
        					.addComponent(logoutConsult))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(118)
        					.addComponent(errorConsult)))
        			.addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jTabbedPane1.addTab("Cart", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(new Color(255, 192, 203));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.setBackground(new Color(255, 240, 245));
        jLabel1 = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        fnameTxt.setBackground(new Color(255, 240, 245));
        jLabel2 = new javax.swing.JLabel();
        lnameTxt = new javax.swing.JTextField();
        lnameTxt.setBackground(new Color(255, 240, 245));
        jLabel3 = new javax.swing.JLabel();
        cnpTxt = new javax.swing.JTextField();
        cnpTxt.setBackground(new Color(255, 240, 245));
        createPatientSecret = new javax.swing.JButton();
        deletePatientSecret = new javax.swing.JButton();
        editPatientSecret = new javax.swing.JButton();
        logoutPatientSecret = new javax.swing.JButton();
        errorPatient = new javax.swing.JLabel();
        
                jTable1.setModel(new DefaultTableModel(
                	new Object[][] {
                		{null, null, null, null},
                		{null, null, null, null},
                		{null, null, null, null},
                		{null, null, null, null},
                	},
                	new String[] {
                		"Id", "Name", "Price", "Quantity"
                	}
                ));
                jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable1MouseClicked(evt);
                    }
                });
                jScrollPane1.setViewportView(jTable1);
                
                        jLabel1.setText("Name:");
                        
                                jLabel2.setText("Price:");
                                
                                        jLabel3.setText("Quantity:");
                                        
                                                createPatientSecret.setText("Create");
                                                createPatientSecret.addActionListener(new java.awt.event.ActionListener() {
                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                        createPatientSecretActionPerformed(evt);
                                                    }
                                                });
                                                
                                                        deletePatientSecret.setText("Delete");
                                                        deletePatientSecret.addActionListener(new java.awt.event.ActionListener() {
                                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                deletePatientSecretActionPerformed(evt);
                                                            }
                                                        });
                                                        
                                                                editPatientSecret.setText("Edit");
                                                                editPatientSecret.addActionListener(new java.awt.event.ActionListener() {
                                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                        editPatientSecretActionPerformed(evt);
                                                                    }
                                                                });
                                                                        
                                                                                logoutPatientSecret.setText("Logout");
                                                                                logoutPatientSecret.addActionListener(new java.awt.event.ActionListener() {
                                                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                                        logoutPatientSecretActionPerformed(evt);
                                                                                    }
                                                                                });
                                                                                
                                                                                        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                                                                                        jPanel1Layout.setHorizontalGroup(
                                                                                        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                                        		.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        			.addContainerGap()
                                                                                        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                                                                        				.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        					.addComponent(logoutPatientSecret)
                                                                                        					.addGap(36))
                                                                                        				.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                                        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                                                                                        						.addComponent(jLabel1)
                                                                                        						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
                                                                                        					.addGap(10)
                                                                                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                                                        						.addComponent(lnameTxt, GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                                                                        						.addComponent(fnameTxt)
                                                                                        						.addComponent(cnpTxt))
                                                                                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                                        						.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                        							.addComponent(errorPatient)
                                                                                        							.addGap(53))
                                                                                        						.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        							.addGap(99)
                                                                                        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                                        								.addComponent(createPatientSecret, GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                                                                                        								.addComponent(editPatientSecret, GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                                                                                        								.addComponent(deletePatientSecret, GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                                                                                        							.addContainerGap())))))
                                                                                        		.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        			.addGap(23)
                                                                                        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addContainerGap(252, Short.MAX_VALUE))
                                                                                        );
                                                                                        jPanel1Layout.setVerticalGroup(
                                                                                        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                                        		.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        			.addContainerGap()
                                                                                        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                                        				.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        					.addGap(109)
                                                                                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                                                                        						.addComponent(fnameTxt, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                                                                        						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
                                                                                        					.addGap(18)
                                                                                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                                                                        						.addComponent(lnameTxt, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                                                                        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
                                                                                        					.addGap(18)
                                                                                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                                                                        						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                                                                                        						.addComponent(cnpTxt, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)))
                                                                                        				.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        					.addGap(103)
                                                                                        					.addComponent(createPatientSecret)
                                                                                        					.addGap(18)
                                                                                        					.addComponent(deletePatientSecret)
                                                                                        					.addGap(21)
                                                                                        					.addComponent(editPatientSecret)))
                                                                                        			.addGap(56)
                                                                                        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                                                                        				.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        					.addComponent(logoutPatientSecret)
                                                                                        					.addGap(27))
                                                                                        				.addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        					.addComponent(errorPatient)
                                                                                        					.addGap(124)))
                                                                                        			.addGap(27))
                                                                                        );
                                                                                        jPanel1.setLayout(jPanel1Layout);
                                                                                        
                                                                                                jTabbedPane1.addTab("Product", jPanel1);

        pack();
    }// </editor-fold>                        

    private void createPatientSecretActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    	errorPatient.setText("");
    	secretaryController.AddNewProduct(fnameTxt.getText(), Integer.parseInt(lnameTxt.getText()), Integer.parseInt(cnpTxt.getText()));
    }                                                   

    private void deletePatientSecretActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    	errorPatient.setText("");
    	secretaryController.DeleteProduct();
    }                                                   

    private void editPatientSecretActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    	errorPatient.setText("");
    	secretaryController.EditProduct(fnameTxt.getText(), Integer.parseInt(lnameTxt.getText()), Integer.parseInt(cnpTxt.getText()));
    
    }                                                 

    private void logoutPatientSecretActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    	this.dispose();
    	_loginView.setVisible(true);
    }                                                   

    private void createConsultActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	errorConsult.setText("");
    	secretaryController.AddNewCart(fnameDoctorTxt.getText(), lnameDoctorTxt.getText(),Integer.parseInt(cnpPatientTxt.getText()) );
    }                                             

    private void deleteConsultActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	errorConsult.setText("");
    	secretaryController.DeleteCart();
    }                                             

    private void editConsultActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	errorConsult.setText("");
    	//secretaryController.EditCart(dateTxt.getText());
    }                                           

    private void logoutConsultActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	this.dispose();
    	_loginView.setVisible(true);
    }                                             
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    	int index = jTable1.getSelectedRow();
    	fnameTxt.setText(jTable1.getValueAt(index, 1).toString());
    	lnameTxt.setText(jTable1.getValueAt(index, 2).toString());
    	cnpTxt.setText(jTable1.getValueAt(index, 3).toString());

        
    }
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    	int index = jTable2.getSelectedRow();
    	//dateTxt.setText(jTable2.getValueAt(index, 3).toString());
    	secretaryController.SetFields(jTable2.getValueAt(index, 1).toString(), jTable2.getValueAt(index, 2).toString());
    }
    private javax.swing.JTextField cnpPatientTxt;
    private javax.swing.JTextField cnpTxt;
    private javax.swing.JButton createConsult;
    private javax.swing.JButton createPatientSecret;
    private javax.swing.JButton deleteConsult;
    private javax.swing.JButton deletePatientSecret;
    private javax.swing.JButton editConsult;
    private javax.swing.JButton editPatientSecret;
    private javax.swing.JLabel errorConsult;
    private javax.swing.JLabel errorPatient;
    private javax.swing.JTextField fnameDoctorTxt;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField lnameDoctorTxt;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JButton logoutConsult;
    private javax.swing.JButton logoutPatientSecret;
    // End of variables declaration                   
	@Override
	public void SetController(RegularUserController controller) {
		// TODO Auto-generated method stub
		secretaryController = controller;
	}

	@Override
	public void UpdateProductView() {
		// TODO Auto-generated method stub
		secretaryController.SetProducts();
	}
	
	@Override
	public void UpdateCartView() {
		// TODO Auto-generated method stub
		secretaryController.SetCarts();
	}

	@Override
	public void SetProductsInGrid(List<Product> patients) {
		// TODO Auto-generated method stub
		String[][] obj = new String[patients.size()][4];
    	for(int i=0;i<patients.size();i++){
    			obj[i][0]=""+patients.get(i).getId();
    			obj[i][1]=patients.get(i).getName();
    			obj[i][2]=""+patients.get(i).getPrice();
    			obj[i][3]=""+patients.get(i).getQuantity();
    			
    		
    	}
    	jTable1.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                new String [] {
                		"Id", "Name",  "Price", "Quantity"
                    }
            ));
	}

	/*@Override
	public void AddNewPatient(Patient patient, Boolean error, String errorMsg) {
		// TODO Auto-generated method stub
		errorPatient.setText(errorMsg);
	}*/

	@Override
	public void DeleteProduct(Product patient, Boolean error, String errorMsg) {
		// TODO Auto-generated method stub
		errorPatient.setText(errorMsg);
	}

	@Override
	public void EditProduct(Boolean error, String errorMsg) {
		// TODO Auto-generated method stub
		errorPatient.setText(errorMsg);
	}

	/*@Override
	public void FindProduct(Product patient, Boolean error, String errorMsg) {
		// TODO Auto-generated method stub
		if (error == false)
        {
			jTable1.removeAll();
            String[][] obj = new String[1][7];
        	obj[0][0]=""+patient.getId();
        	obj[0][1]=patient.getFirstName();
        	obj[0][2]=patient.getLastName();
        	obj[0][3]=patient.getCnp();
        	obj[0][4]=patient.getAddress();
        	obj[0][5]=patient.getDoB();
        	obj[0][6]=patient.getPhone();
        		
        	jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    obj,
                    new String [] {
                    		"Id", "FirstName", "LastName", "CNP", "Address", "BirthDate", "Phone"
                        }
                ));
			errorPatient.setText(errorMsg);
        }
        else
        	errorPatient.setText(errorMsg);
	}
*/
	@Override
	public Product GetSelectedProductFromGrid() {
		// TODO Auto-generated method stub
		if (jTable1.getSelectedRowCount() > 0)
        {
        	int row = jTable1.getSelectedRow();
        	Product patient = new Product();
        	patient.setId(Integer.parseInt(jTable1.getValueAt(row, 0).toString()));
        	patient.setName(jTable1.getValueAt(row, 1).toString());
        	patient.setPrice(Integer.parseInt(jTable1.getValueAt(row, 2).toString()));
        	patient.setQuantity(Integer.parseInt(jTable1.getValueAt(row, 3).toString()));

            return patient;
        }
        else
        	errorPatient.setText("Select a row from table!");
        return null;
	}

	@SuppressWarnings({ "rawtypes", "unchecked", "serial" })
	@Override
	public void SetBuyersInList(List<User> users) {
		// TODO Auto-generated method stub
		String[] item = new String[users.size()];
		for(int i=0;i<users.size();i++){
			item[i]=""+users.get(i).getFirstName()+" "+users.get(i).getLastName();
		}
    	jList1.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return item.length; }
            public Object getElementAt(int i) { return item[i]; }
        });
	}

	@Override
	public void SetCartsInGrid(List<Cart> consultations) {
		// TODO Auto-generated method stub
		String[][] obj = new String[consultations.size()][3];
		if(consultations.size() > 0 )
		{
			for(int i=0;i<consultations.size();i++){
    			obj[i][0]=""+consultations.get(i).getId();
    			obj[i][1]=consultations.get(i).getId_product();
    			obj[i][2]=consultations.get(i).getId_buyer();
    		
			}
			jTable2.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                new String [] {
                		"Id", "Id_Product", "Id_Buyer"
                    }
            ));
		}
	}

	@Override
	public void AddNewCart(Cart consult, Boolean error, String errorMsg) {
		// TODO Auto-generated method stub
		errorConsult.setText(errorMsg);
	}

	@Override
	public void DeleteCart(Cart consult, Boolean error, String errorMsg) {
		// TODO Auto-generated method stub
		errorConsult.setText(errorMsg);
	}

	@Override
	public void EditCart(Boolean error, String errorMsg) {
		// TODO Auto-generated method stub
		errorConsult.setText(errorMsg);
	}

	@Override
	public void SetFields(String fname, String lname) {
		// TODO Auto-generated method stub
		fnameDoctorTxt.setText(fname);
		lnameDoctorTxt.setText(lname);
	}

	@Override
	public Cart GetSelectedCartFromGrid() {
		// TODO Auto-generated method stub
		if (jTable2.getSelectedRowCount() > 0)
        {
        	int row = jTable2.getSelectedRow();
        	Cart consult = new Cart();
        	consult.setId(Integer.parseInt(jTable2.getValueAt(row, 0).toString()));
        	consult.setId_product(jTable2.getValueAt(row, 1).toString());
        	consult.setId_buyer(jTable2.getValueAt(row, 2).toString());
        	
            return consult;
        }
        else
        	errorConsult.setText("Select a row from table!");
        return null;
	}

	@Override
	public void AddNewProduct(String errorMsg) {
		// TODO Auto-generated method stub
		errorPatient.setText(errorMsg);

	}
}
